<?php
$lang = array
(
	'url_error'	=> '无效访问，请返回。',
	'submit' => '提 交',
	'select_all' => '全选',
	'reset' => '重 置',
	'tips' => '技巧提示',
	'name' => '名称',
	'none' => '无',
	'default' => '默认',
	'use_default' => '- 使用默认 -',
	'unknown' => '未知',
	'yes' => '是',
	'no' => '否',
	'ok' => ' 确 定 ',
	'cancel' => ' 取 消 ',
	'unlimited' => '无限制',
	'del' => '删?',
	'delete' => '删除',
	'update' => '修改',
	'remove' => '移动',
	'merge' => '合并',
	'merge_alert' => '与同级分类合并',
	'undelete' => '还原',
	'invalidate' => '否决',
	'validate' => '通过',
	'ignore' => '忽略',
	'reward' => '悬赏',
	'answer' => '回答',
	'browse' => '浏览',
	'status' => '状态',
	'sortname' => '分类名称',
	'arrange' => '排列顺序',
	'belong_to_sort' => '所属分类',
	'select_sort' => '选择分类',
	'->' => '→',
	'operator' => '操作者',
	'reason' => '原因',
	'ques_list' => '问题列表',
	'empty_ques' => '清空问题',
	'author' => '作者',
	'subject' => '标题',
	'nosubject' => '无标题',
	'message' => '内容',
	'asktime' => '提问时间',
	'endtime' => '结束时间',
	'description' => '描述',
	'copyright' => '版权信息',
	'attachment' => '附件',
	'filename' => '文件名',
	'version' => '版本',
	'time' => '时间',
	'type' => '类型',
	'size' => '尺寸',
	'operation' => '操作',
	'ip' => 'IP 地址',
	'usergroup' => '用户组',
	'admingroup' => '管理组',
	'rank' => '发帖数级别',
	'members' => '会员',
	'guest' => '游客',
	'anonymous' => '匿名',
	'username' => '用户名',
	'password' => '密码',
	'safecode' => '安全码',
	'birthday' => '生日',
	'year' => '年',
	'month' => '月',
	'day' => '日',
	'credits' => '积分',
	'credits_id' => '积分代号',
	'credits_title' => '积分名称',
	'credits_unit' => '积分单位',
	'rmb' => '人民币',
	'rmb_yuan' => '元',
	'email' => 'Email',
	'thread' => '主题',
	'action' => '动作',
	'other' => '其他',
	'add_new' => '新增:',
	'select' => '请选择',
	'search' => '搜索',
	'return' => '返回',
	'copy' => '复制',
	'preview' => '预览',
	'all' => '全部',
	'download' => '下载',
	'detail' => '详情',
	'import' => '导入',
	'export' => '导出',
	'edit' => '编辑',
	'intro' => '推荐',
	'intro_yes' => '已推荐',
	'intro_no' => '未推荐',
	'display_order' => '显示顺序',
	'available' => '可用',
	'start_time' => '起始时间',
	'end_time' => '终止时间',
	'validity' => '有效期',
	'pm' => '短消息',
	'custom_status' => '自定义头衔',
	'case_insensitive' => '不区分大小写',
	'new_windows' => '打开新窗口',
	'first_page' => '首页',
	'tail_page' => '尾页',
	'nosolve' => '待解决',
	'solve' => '已解决',
	'voting' => '投票中',
	'closed' => '已关闭',
	
	'cyask_message' => 'cyask 提示',
	'message_redirect' => '如果您的浏览器没有自动跳转，请点击这里',
	'message_return' => '[ 点击这里返回上一页 ]',

	'admincp' => '系统设置',
	'header_offical' => 'Cyask 官方网站',
	'header_csm' => 'cyask 问答管理系统',
	'header_home' => '网站首页',
	'safecode_required' => '《知道》管理员身份登录',
	'login_invalid' => '用户不存在，或已被删除。',
	'password_error' => '登录密码错误。',
	
	'home' => '首页',
	'home_welcome_to' => '欢迎来到',
	'home_onlines' => '系统设置在线用户 - 斜体字表示尚未通过密码验证',
	'home_onlines_errors' => '错误次数',
	'home_online_regip' => '注册 IP',
	'home_onlines_ip' => '访问 IP',

	'home_notes' => '管理团队留言',
	'home_threads_posts' => '以下主题或回复等待您的验证',
	'home_mod_threads' => '等待审核的主题数',
	'home_mod_posts' => '等待审核的回复数',
	'home_delete_threads' => '回收站中的主题数',

	'home_stuff' => '快捷方式',
	'home_php_lookup' => 'PHP 函数查询',
	'home_edit_sort' => '编辑分类',
	'home_edit_group' => '编辑用户组',
	'home_edit_member' => '编辑用户',
	'home_sys_info' => '系统信息',
	'home_environment' => '操作系统及 PHP',
	'home_database' => 'MySQL 版本',
	'home_upload_perm' => '上传许可',
	'home_database_size' => '当前数据库尺寸',
	'home_attach_size' => '当前附件尺寸',

	'home_dev' => 'cyask! 开发团队',
	'home_dev_copyright' => '版权所有',
	'home_dev_team' => '开发与支持团队',
	'home_dev_addons' => 'Hack 与插件设计',
	'home_dev_skins' => '界面美工设计',
	'home_dev_enterprise_site' => '公司网站',
	'home_dev_project_site' => '产品官方网站',
	'home_dev_community' => '产品技术支持',
	'home_commend_new' => 'cyask 最新推荐主题',

	'data_count' => '数据统计',
	'data_user_totalcount' => '总计注册用户数',
	'data_user_todaycount' => '今日注册用户数',
	'data_user_weekcount' => '本周注册用户数',
	'data_user_monthcount' => '本月注册用户数',
	'data_comment_totalcount' => '总计评论数',
	'data_comment_todaycount' => '今日评论数',
	'data_comment_weekcount' => '本周评论数',
	'data_comment_monthcount' => '本月评论数',
	
	'menu_home' => '首页',
	'menu_runwizard' => '快速设置向导',

	'menu_settings' => 'cyask 选项',

	'menu_moderation' => '管理选项',

	'menu_sort' => '分类管理',
	'menu_sort_add' => '添加分类',
	'menu_sort_edit' => '编辑分类',
	'menu_sort_merge' => '合并分类',
	'menu_sort_rules' => '分类规则',
	'menu_parent_sort' => '返回上级分类',
	'menu_merge_to'  => '合并到',
	'menu_sort1_add' => '建一级分类',
	'menu_sort2_add' => '建二级分类',
	'menu_children_sort' => '下级子分类',
	'menu_no_sort' => '还没有建立任何分类',
	'menu_edit_ques' => '编辑问题',
	'menu_supply_ques' => '问题补充',
	'menu_sort_ques' => '分类的问题',
	'menu_nosolve_ques' => '待解决问题',
	'menu_solve_ques' => '已解决问题',
	'menu_vote_ques' => '投票中问题',
	'menu_intro_ques' => '推荐的问题',
	'menu_close_ques' => '关闭的问题',
	'menu_answer_response' => '回答的评论',
	'menu_groups' => '分组与级别',
	'menu_usergroups' => '用户组',
	'menu_admingroups' => '管理组',
	'menu_ranks' => '发帖数级别',

	'menu_members' => '用户管理',
	'menu_members_add' => '添加用户',
	'menu_members_edit' => '编辑用户',
	'menu_members_merge' => '合并用户',
	'menu_members_profile_fields' => '用户栏目定制',
	'menu_members_ipban' => '禁止 IP',
	'menu_logout_sys' => '退出管理',
	'menu_styles' => '界面风格',
	'menu_styles_templates' => '模板编辑',

	'menu_moderate' => '审核管理',
	'menu_moderate_modmembers' => '审核新用户',
	'menu_moderate_modthreads' => '审核新主题',
	'menu_moderate_modreplies' => '审核新回复',
	'menu_moderate_recyclebin' => '主题回收站',

	'menu_database' => '数据库',
	'menu_database_export' => '资料备份',
	'menu_database_import' => '资料恢复',
	'menu_database_query' => '数据库升级',
	'menu_database_optimize' => '数据表优化',

	'menu_tools' => 'cyask 工具',
	'menu_tools_javascript' => 'JS 调用向导',
	'menu_tools_updatecaches' => '更新缓存',
	'menu_tools_updatecounters' => '更新论坛统计',
	'menu_tools_fileperms' => '文件权限检查',
	'menu_tools_check' => '检查',

	'menu_logs' => '运行记录',
	'menu_logs_login' => '密码错误记录',
	'menu_logs_rating' => '用户评分记录',
	'menu_logs_credit' => '积分交易记录',
	'menu_logs_mod' => '版主管理记录',
	'menu_logs_medal' => '勋章授予记录',
	'menu_logs_ban' => '禁止用户记录',
	'menu_logs_admincp' => '后台访问记录',
	'menu_logs_error' => '系统错误记录',
	
	'usergroups_system_0' => '普通用户',
	'usergroups_system_1' => '管理员',
	'usergroups_system_2' => '超级版主',
	'usergroups_system_3' => '版主',
	'usergroups_system_4' => '禁止发言',
	'usergroups_system_5' => '禁止访问',
	'usergroups_system_6' => '用户IP被禁止',
	'usergroups_system_7' => '游客',
	'usergroups_system_8' => '等待验证',

	'members_edit_credits' => '编辑用户积分',
	'members_edit_credits_ranges' => '用户组积分上下限',
	'members_edit_credits_reason' => '修改用户积分的理由:',
	'members_edit_credits_reason_comment' => '如果您修改了用户的积分资料，请输入操作理由，系统将把理由记录在用户评分记录中，以供日后查看',

	'members_edit_medals_grant' => '授予',
	'members_edit_medals_revoke' => '收回',
	'members_edit_medals_unavailable' => '不可用',
	'members_edit_medals_reason' => '授予/收回勋章的理由:',
	'members_edit_medals_reason_comment' => '如果您修改了用户的勋章资料，请输入操作理由，系统将把理由记录在勋章授予记录中，以供日后查看',

	'members_search' => '搜索用户',
	'members_delete' => '删除用户',

	'database_method' => '方式',
	'database_shell' => 'Shell',
	'database_multivol' => '多卷',
	'database_volume' => '卷号',
	'database_export_tips' => '<ul><li>数据备份功能根据您的选择备份全部论坛帖子和设置数据，导出的数据文件可用“数据恢复”功能或 phpMyAdmin 导入。</ul><ul><li>全部备份均不包含模板文件和附件文件。模板、附件和用户自定义头像的备份只需通过 FTP 等下载 ./templates, ./attachments 和 ./customavatars 目录即可，Cyask! 不提供单独备份。</ul><ul><li>MySQL Dump 的速度比 Cyask! 分卷备份快很多，但需要服务器支持相关的 Shell 权限，同时由于 MySQL 本身的兼容性问题，通常进行备份和恢复的服务器应当具有相同或相近的版本号才能顺利进行。因此 MySQL Dump 是有风险的：一旦进行备份或恢复操作的服务器其中之一禁止了 Shell，或由于版本兼容性问题导致导入失败，您将无法使用 MySQL Dump 备份或由备份数据恢复；Cyask! 分卷备份没有此限制。</ul><ul><li>数据备份选项中的设置，仅供高级用户的特殊用途使用，当您尚未对数据库做全面细致的了解之前，请使用默认参数备份，否则将导致备份数据错误等严重问题。</ul>',
	'database_export_type' => '数据备份类型',
	'database_export_full' => '全部备份',
	'database_export_full_comment' => '包括全部论坛数据表数据',
	'database_export_standard' => '标准备份(推荐)',
	'database_export_standard_comment' => '包括常用的数据表数据',
	'database_export_mini' => '最小备份',
	'database_export_mini_comment' => '仅包括用户、板块设置及系统设置数据',
	'database_export_custom' => '自定义备份',
	'database_export_custom_comment' => '根据需要自行选择需要备份的数据表',
	'database_export_custom_select_all' => '全选',
	'database_export_method' => '数据备份方式',
	'database_export_shell' => '系统 MySQL Dump (Shell) 备份',
	'database_export_multivol' => 'cyask! 分卷备份 - 文件长度限制(kb)',
	'database_export_options' => '数据备份选项',
	'database_export_options_extended_insert' => '使用扩展插入(Extended Insert)方式',
	'database_export_options_add_set_names' => '添加字符集限定(SET NAMES)',
	'database_export_options_sql_compatible' => '建表语句格式',
	'database_export_options_charset' => '强制字符集',
	'database_export_filename' => '备份文件名:',
	'database_export_filename_confirm' => '注意: \n\n数据文件保存在服务器的可见目录下，其他人有    \n可能下载得到这些文件，这是不安全的。因此请    \n在使用随机文件名的同时，适时删除备份文件。',
	'database_export_file' => '数据备份记录',
	'database_export_cyask_table' => 'cyask! 数据表',

	'database_import' => '数据恢复',
	'database_import_confirm' => '导入和当前cyask 版本不一致的数据极有可能产生无法解决的故障，您确定继续吗？',
	'database_import_tips' => '<ul><li>本功能在恢复备份数据的同时，将全部覆盖原有数据，请确定恢复前已将网站关闭，恢复全部完成后可以将网站重新开放。</ul><ul><li>数据恢复功能只能恢复由当前版本 cyask! 导出的数据文件，其他软件导出格式可能无法识别。</ul><ul><li>从本地恢复数据需要服务器支持文件上传并保证数据尺寸小于允许上传的上限，否则只能使用从服务器恢复。</ul><ul><li>如果您使用了分卷备份，只需手工导入文件卷 1，其他数据文件会由系统自动导入。</ul>',
	'database_import_from_server' => '从服务器(填写文件名或 URL):',
	'database_import_from_local' => '从本地文件:',
	'database_run_query' => 'Cyask! 数据库升级 - 请将数据库升级语句粘贴在下面',
	'database_run_query_comment' => '注意: 为确保升级成功，请不要修改 SQL 语句的任何部分。',
	'database_optimize_tips' => '<ul><li>数据表优化可以去除数据文件中的碎片，使记录排列紧密，提高读写速度。</ul>',
	'database_optimize_opt' => '优化?',
	'database_optimize_table_name' => '数据表',
	'database_optimize_data' => '数据',
	'database_optimize_rows' => '记录数',
	'database_optimize_index' => '索引',
	'database_optimize_frag' => '碎片',
	'database_optimize_used' => '尺寸',
	
	'site_name' => '网站名称',
	'admin_email' => '管理员邮箱',
	'meta_description' => 'meta description',
	'meta_keywords' => 'meta keywords',
	'count_show_sort1' => '首页一级分类显示数量',
	'count_show_sort2' => '首页二级分类显示数量',
	'count_show_intro' => '首页推荐问题显示数量',
	'count_show_nosolve' => '首页待解决问题显示数量',
	'count_show_solve' => '首页已解决问题显示数量',
	'count_show_share' => '首页知识分享显示数量',
	'count_show_note' => '首页公告显示数量',
	'count_ques_exceed' => '每日限制提问数量',
	'count_ip_register' => '每个IP允许注册用户数',
	'overdue_days' => '问题过期天数',
	'score_answer' => '回答问题奖励积分',
	'score_share'=> '知识分享奖励积分',
	'score_adopt' => '回答被采纳奖励积分',
	'score_register'=> '新注册奖励积分',
);
	
	
$msglang = array
(
	'write_sortname' => '请填写分类名称！',
	'del_alert' => '你确定要删除问题吗？',
	'no_question' => '该分类还没有任何问题',
	'undefined_action' => ' 未定义操作。',
	'noaccess' => '您没有权限访问系统设置。',
	'noaccess_ip' => '对不起，管理员设定了只有特定 IP 地址范围才能访问系统设置，您的地址不在被允许的范围内。',
	'action_noaccess' => '对不起，管理员设定了您没有权限使用本功能。',

	'settings_gzip_invalid' => '当前 PHP 版本不支持 Gzip 压缩，请返回修改。',
	'settings_maxonlines_invalid' => '指定的最大在线人数超过 65535，请返回修改。',
	'settings_creditsformula_invalid' => '积分公式包含无效变量或运算符，请返回修改。',
	'settings_ipaccess_invalid' => '操作错误！您自己的 IP 在 IP 访问列表以外，请返回修改。',
	'settings_adminipaccess_invalid' => '操作错误！您自己的 IP 在管理员后台 IP 访问列表以外，请返回修改。',
	'settings_credits_title_invalid' => '您没有为全部被启用的积分设置积分名称，请返回修改。',
	'settings_creditstrans_invalid' => '交易积分必须是已经被启用的积分类型，请返回修改。',
	'settings_update_succeed' => 'cyask! 选项成功更新。',


	'announce_nonexistence' => '指定的公告不存在或无权编辑，请返回。',
	'announce_time_invalid' => '对不起，您没有输入起始时间或您输入的终止时间不正确，请返回修改。',
	'announce_invalid' => '您必须输入公告标题和内容，请返回修改。',
	'announce_succeed' => '公告成功编辑。',
	'announce_update_succeed' => '公告成功更新。',


	'members_add_invalid' => '您没有填写完整用户资料，请返回修改。',
	'members_add_username_duplicate' => '用户名已经存在，请返回修改。',
	'members_add_uid_invalid' => '指定范围内没有可用的 UID，无法成功分配，请返回修改。',
	'members_add_succeed' => '用户 $newusername(UID $uid) 添加成功。',
	'members_search_invalid' => '您没有提供搜索的条件，请返回修改。',
	'members_delete_confirm' => '本操作不可恢复，您确定要删除符合条件的 $membernum 个用户吗？',
	'members_delete_succeed' => '符合条件的 $numdeleted 个用户被成功删除。',
	'members_edit_nonexistence' => '指定用户不存在，请返回。',
	'members_edit_illegal' => '您不能编辑特殊用户，请返回。',
	'members_edit_reason_invalid' => '您没有输入执行此变更的理由，请返回修改。',
	'members_edit_duplicate' => '新用户名与现有用户重复，请返回修改。',
	'members_edit_succeed' => '用户资料成功更新。',
	'members_edit_groups_toomany' => '您设置了过多的扩展用户组，已超出系统允许的存储容量，请返回修改。',
	'members_edit_groups_illegal' => '过期用户组和用户当前所属用户组相同，请返回修改。',
	'members_edit_groups_succeed' => '用户的用户组属性编辑成功。',
	'members_edit_credits_succeed' => '用户积分成功编辑。',
	'members_edit_medals_nonexistence' => '目前没有可用的勋章，请在“勋章编辑”功能中设定可用的勋章后再编辑。',
	'members_edit_medals_succeed' => '用户勋章成功编辑。',

	'members_newsletter_sm_invalid' => '您没有输入消息的标题或内容，请返回修改。',
	'members_newsletter_succeed' => '论坛通知成功发送。',

	'members_credits_invalid' => '您没有对用户积分进行奖惩，请返回修改。',
	'members_credits_succeed' => '用户积分奖惩成功执行。',
	'members_credits_notify_succeed' => '用户积分奖惩成功执行，并已通知相关用户。',

	
	'database_export_custom_invalid' => '您至少需要选择一个数据表进行备份，请返回修改。',
	'database_export_file_invalid' => '数据文件无法保存到服务器，请检查目录属性。',
	'database_export_multivol_redirect' => '分卷备份: 数据文件 #$volume 成功创建，程序将自动继续。',
	'database_export_succeed' => '数据成功备份至服务器 <a href=\"$filename\">$filename</a> 中。',
	'database_export_filename_invalid' => '您没有输入备份文件名或文件名中使用了敏感的扩展名，请返回修改。',
	'database_export_multivol_succeed' => '恭喜您，全部 $volume 个备份文件成功创建，备份完成。\n<br>$filelist',
	'database_export_dest_invalid' => '目录不存在或无法访问，请检查 ./askdata/ 目录。',
	'database_import_multivol_succeed' => '分卷数据成功导入论坛数据库。',
	'database_import_file_illegal' => '数据文件不存在: 可能服务器不允许上传文件或尺寸超过限制。',
	'database_import_format_illegal' => '数据文件非 Cyask 格式，无法导入。',
	'database_import_multivol_prompt' => '分卷数据成功导入数据库，您需要自动导入本次其他的的备份吗？',
	'database_import_multivol_redirect' => '数据文件 #$dumpinfo[volume] 成功导入，程序将自动继续。',
	'database_import_succeed' => '数据成功导入论坛数据库。',
	'database_shell_fail' => 'Shell 权限被禁止或服务器不支持，无法使用 MySQL Dump 方式备份或恢复数据，请返回。',
	'database_file_delete_succeed' => '指定备份文件成功删除。',
	'database_file_delete_invalid' => '您没有选择要删除的备份文件，请返回。',
	'database_run_query_invalid' => '升级错误，MySQL 提示: $sqlerror',
	'database_run_query_succeed' => 'Cyask 数据结构成功升级。',


	'attachtypes_succeed' => '附件类型成功更新。',
	'update_cache_succeed' => '全部缓存更新完毕。',
	'logout_succeed' => '您已成功退出系统设置。',

	'prune_succeed' => '符合条件的 $deletedthreads 篇主题和 $deletedposts 篇帖子被删除。',
	'prune_pm_range_invalid' => '您没有输入要删除短消息的时间范围，请返回修改。',
	'prune_pm_confirm' => '本操作不可恢复，您确定要删除符合条件的 $pmnum 条短消息吗？',
	'prune_pm_succeed' => '符合条件的 $num 条短消息成功删除。',

	'styles_export_invalid' => '指定的风格不存在，无法导出。',
	'styles_delete_invalid' => '您不能直接删除系统默认的风格，请返回选择其他风格为默认后再进行删除。',
	'styles_edit_succeed' => '界面方案成功更新。',
	'styles_import_data_invalid' => '界面数据文件已损坏，无法导入，请返回。',
	'styles_import_version_invalid' => '导出界面所用 Cyask ($stylearray[version])与当前版本($version)不一致，请返回。',
	'styles_import_directory_invalid' => '模板目录无法自动建立，请设置 $basedir 目录属性为 777<br>或通过 FTP 建立目录 $stylearray[directory] 并设置属性为 777。',
	'styles_import_succeed_renamed' => '导入风格或模板名称与现有重复，已被自动重命名。界面方案成功导入。',
	'styles_import_succeed' => '界面方案成功导入。',
	'styles_edit_variable_duplicate' => '新增的替换变量名已经存在，请返回修改。',
	'styles_edit_variable_illegal' => '新增的替换变量名称不合法，请返回修改。',
	'styles_edit_succeed' => '界面方案成功更新。',

	'templates_directory_invalid' => '模板目录 $directory 不存在于 ./templates 中，或以 \"/\" 结尾，请返回修改。',
	'templates_new_directory_invalid' => '您没有填写模板所在目录，请返回修改。',
	'templates_default_directory_invalid' => '您不能修改默认模板的目录设置，请返回。',
	'templates_delete_invalid' => '您不能删除默认模板，请返回。',
	'templates_update_succeed' => '模板套系成功更新。',
	'templates_edit_nonexistence' => '指定模板套系不存在，请返回。',
	'templates_edit_invalid' => '指定文件 $template[directory]/$fn 无法写入，<br>若需在线编辑，请将该文件和所在目录属性设置为 777。',
	'templates_edit_succeed' => '指定模板成功编辑，现在将转入模板列表。',
	'templates_add_invalid' => '指定模板套系不存在或已被删除，请返回。',
	'templates_add_duplicate' => '新增模板已经存在，请返回选择其他名称。',
	'templates_add_file_invalid' => '指定文件 $template[directory]/$name.htm 无法写入，<br>若需在线编辑，请将该文件和所在目录属性设置为 777。',
	'templates_add_succeed' => '指定模板成功添加，现在将转入模板编辑页。',
	'templates_delete_confirm' => '本操作不可恢复，您确定要删除模板 $fn 吗？',
	'templates_delete_succeed' => '指定模板成功删除，现在将转入模板列表。',
	'templates_delete_fail' => '程序无权删除模板文件，请用 FTP 登录后再试。',

	'attachments_forum_invalid' => '您没有选择附件所在论坛，请返回修改。',
	'attachments_edit_succeed' => '附件列表成功更新。',
	'attachments_edit_invalid' => '您没有选择要删除的附件，请返回修改。',

	
	'csscache_update' => 'CSS缓存文件已更新',
);

?>